components/AuthButtons.tsx, components/Navbar.tsx, package-lock.json, package.json
issue #7 
I focused on **revamping the `Navbar.tsx` and `AuthButtons.tsx` components** to bring a **modern, polished, and interactive experience** that aligns with premium SaaS-level UI.
---
* Search input felt disconnected from the dark theme.
* Mobile search toggle lacked smooth animations.
* Minimal visual hierarchy and interactivity.
* **Glassmorphism Search Bar** with integrated dark theme styling.
* **Animated Focus States** (scale + glow).
* **Gradient & Blur Effects** for a premium feel.
* **Mobile Search Transition** using Framer Motion (smooth expand/collapse).
* **Animated Streak Icon** with pulse & subtle rotation when active.
* **Cohesive Gradient Navbar Background** with professional hover & active states.
---
* Dropdown menu was basic and static.
* Simple hamburger toggle …
=> Enhancement: Navbar Styling and Transitions

app/notes/page.tsx, package-lock.json
Changes:
- Redesigned notes cards layout and icons
- Added hover effects and animations
- Improved footer layout
- Optimized for mobile with fixed responsive view
- Added gradients and shadows for better look
File updated: app/notes/page.jsx
Priority: High – Better UI/UX
---
=> UI/UX: Enhanced Notes page layout, animations, and mobile view

README.md
I have added the license in the readme file at the bottom you can check and update the repository.
=> docs: added MIT license to README

CONTRIBUTING.md
Changed according to file directory
=> Changed Contributing.md

components/ui/input.tsx
fix : #86 
I've added black color to the inputting texts given by user in login , sign up pages.
- Before :
- After :
=> Input text Visibility fixed 

app/notes/page.tsx, app/progress/page.tsx, app/sheet/page.tsx, components/AuthButtons.tsx, components/Navbar.tsx, components/NavbarSheet.tsx
This PR updates the Notes page to use the **global navbar** that is consistent across the entire platform, addressing the design inconsistency issue.
Additionally, it redesigns the Notes cards for better aesthetics and alignment with the platform's overall design language.
* Replaced the Notes page navbar with the **global navbar** for consistent navigation experience.
* Redesigned the Notes cards UI for improved visual appeal and user experience.
* Ensured that the **search questions input** remains **only on the Sheet page** (as it’s the only page with searchable content).
---
* **Consistent Navbar:** The Notes page now uses the same global navbar as all other pages.
* **Improved UI:** Notes cards now have a cleaner and more modern design aligned with the platform’s design system.
* …
=> Fix: Unified Navbar and Enhanced Notes Cards UI

app/api/contributors-points/route.ts, app/contributors/page.tsx, package-lock.json
**Modified contributors page to display Points earned by contributors**
**overall look of the new contributors page**
**Hover effect to visit the profile**
**Legned for the pointing system**
**also included non `GSSoC` tagged members as community contributors**
=> Modified Contributors Page [#Issue 101] 

app/page.tsx, components/AuthButtons.tsx, components/Footer.tsx, components/Navbar.tsx
Reverts saumyayadav25/cpp-dsa-sheet-testing#113
=> Revert "landing page design improved"

CONTRIBUTING.md, package-lock.json
> TLDR: the file lacked info about setting up API KEY's which caused the application to terminate
Updated the CONTRIBUTING.md file with a comprehensive setup guide and improved navigation to help contributors get started more easily as the earlier version was missing on setting up the `environment` and `API KEY`'s properly.
- **Table of Contents**: Added a complete navigation section with clickable links to all major sections
- **Comprehensive Environment Setup**: Detailed instructions for all required environment variables
- **Tech Stack Overview**: Clear explanation of all technologies used in the project
- **Database Setup Options**: Both MongoDB Atlas and local MongoDB setup instructions
- **API Keys Configuration**: Step-by-step guides for Google Gemini AI, GitHub tokens, and JWT …
=> Updated CONTRIBUTING.md with local setup guide

app/timequiz/page.tsx
=> Follow up Fix #145 PR Quiz background Fix

app/(auth)/sign-in/page.tsx, app/(auth)/sign-up/page.tsx, package-lock.json, package.json
fix : #131 
Previously sonner was added in the page.ts, but they not are working because of not adding them in layout.tsx & those toast messages were plain & simple so I added better designed react toast messages to Login , Sign Up pages at each step 
Here's where we will get : 
- When login/signup credentials wrong 
- When correct credentials entered & so they wil get a OTP receiving messages 
- When OTP entered is wrong , if right Successful login /signup message
Pictures of implementation for some of these scenarios
(Wrong credentials case)
(OTP sending stage)
Please review & let me know for any changes further & I can add more pictures if you want to know how they are coming in many other cases.
Thank you!
=> Enhanced Toast mssgs for login/signup

app/privacy-terms/page.tsx, components/Footer.tsx
=> docs: add links to footer

app/api/badges/[userId]/route.ts, app/api/badges/route.ts, app/profile/[userId]/page.tsx, components/AuthButtons.tsx, components/POTD.tsx, components/SheetContent.tsx, package-lock.json
**Description:**
This PR completes the dynamic badge system implementation as described in Issue #52 by integrating frontend functionality with the backend APIs developed in Issue #51. The goal was to create a fully responsive, real-time badge and progress tracking experience that rewards users based on their consistency, topic mastery, and problem-solving milestones.
---
**Detailed Implementation Overview:**
1. **Backend API Integration:**
We utilized the existing backend APIs that provide user progress and badge data. These APIs return comprehensive information about:
* The total number of questions solved by the user.
* The badges the user has earned.
* The current streak or consistency count.
2. **Rendering Dynamic Data on Profile Page:**
The profile page dynamically displays:
* …
=>  Implement Dynamic Badge System for User Milestones and Progress

app/profile/[userId]/Button.tsx, app/profile/[userId]/page.tsx
This PR adds social media sharing capabilities to the **Achievement Badges** section of the Profile page.
Users can now directly share their earned badges to **LinkedIn** and **Twitter (X)** with one click.
The goal is to:
* Increase engagement and visibility for **DSA-Mate**.
* Encourage users to celebrate their progress publicly.
* Lay the groundwork for tracking and analytics in future iterations.
---
* **Added two share buttons** (LinkedIn & Twitter) to each badge card in the **Profile → Achievement Badges** section.
* Used the existing `Button` component for UI consistency.
* LinkedIn:
* Opens `share-offsite` dialog with the DSA-Mate URL (future: direct badge page links).
* Twitter:
* Pre-fills the tweet text with a custom congratulatory message + DSA-Mate URL.
* Added per-badge …
=> Add Social Sharing Buttons for Achievement Badges (LinkedIn & Twitter)

app/notes/page.tsx, package-lock.json, package.json
closes #170 
https://github.com/user-attachments/assets/978f0b72-5a5b-4597-ada9-70579dc24c99
=> added searchbar and favourites in notes

app/api/progress/[userId]/route.ts, app/api/progress/update/route.ts, app/progress/page.tsx, components/ProgressChart.tsx, components/ProgressStats.tsx, components/SheetContent.tsx, models/Progress.model.ts
**Description:**
This PR integrates live backend data into the **Progress Page**, replacing placeholder/mock values with actual user progress information. We have connected the `ProgressStats` and `ProgressCharts` sections to the backend API so they now reflect the user's real problem-solving activity and topic progress.
**Key Changes:**
* **Backend API Integration:**
* Hooked up `ProgressStats` to fetch real-time data from `/api/progress/[userId]`.
* Updated API response mapping to match frontend needs (`easySolved`, `mediumSolved`, `hardSolved`, `totalSolved`, `topicsProgress`, etc.).
* Handled potential `null/NaN` values gracefully to avoid runtime errors.
* **ProgressStats Section:**
* Displays **This Week**, **Daily Average**, **Best Topic**, and **Weekly Goal** using actual user …
=>  Render Real User Data in Progress Page (Stats & Charts)

app/api/leetcode/route.ts, app/cp-tracker/page.tsx, components/LeetCodeDashboard.tsx, components/Navbar.tsx, components/charts/DifficultyDonutChart.tsx, components/charts/SubmissionBarChart.tsx, utils/leetcode.ts
- Fixes #197 
This PR expands the Competitive Programming Tracker's functionality by introducing comprehensive statistics and visualizations for LeetCode users. Building on the existing Codeforces integration, users can now input their LeetCode handle to view a detailed analysis of their problem-solving journey and contest performance.
This update aims to provide a more holistic tracking experience by supporting another major competitive programming platform.  However for other platforms I find out there is no specific developers API which we can use , and for the ones which it is are not so used so will try if further asked 🚀
- **Implemented LeetCode API Integration**: Added a new utility to fetch user data from LeetCode, including solved counts, contest history, and topic breakdowns.
- …
=> Advanced graphical stats for leetcode

.github/pull_request_template.md, components/AuthButtons.tsx
- Fixes #174   , Fixes previous PR - #196 
Previous commit removed the user dashboard page , fixed that issue
- Added previously removed dashboard
- When user clicks on image icon it redirects to profile settings page
- When clicks on name in the button redirects to user dashboard
1. Go to profile & click on image icon the edit icon redirects to -> `/profile_pic/settings/avatar`
2. Click on name beside the profile ->redirects to User stats , badge dashboard
---
No need to add any labels for this @saumyayadav25
=> Following up previous merge #196

app/api/progress/[userId]/route.ts, app/contributors/page.tsx, app/cp-tracker/page.tsx, app/notes/page.tsx, app/page.tsx, app/privacy-terms/page.tsx, app/profile/[userId]/page.tsx, app/profile_pic/settings/avatar/page.tsx, app/progress/page.tsx, app/sheet/page.tsx, app/timequiz/page.tsx, components/AuthButtons.tsx, components/Navbar.tsx, components/NavbarSheet.tsx
Previously, the **streak counter** was only updating correctly on the **Progress Page**, since the streak logic and API calls were isolated there. On other pages (e.g., Navbar streak symbol), the streak data was **stale** and didn’t reflect updates when a user solved a problem or revisited the site.
This PR ensures that the streak is **synchronized globally across the application** so it always displays the correct value, no matter which page the user is on.
---
* Streak updates were scoped to the **Progress Page** only.
* Other pages (Navbar, global components) were not receiving the latest streak value.
* Caused by:
* Isolated API calls → streak data was fetched only on the Progress Page.
* No centralized/global state → components outside the Progress Page relied on outdated values.
--- …
=>  Global Streak Synchronization Across Navbar & Pages

app/api/generate-feedback/route.ts, app/api/generate-quiz/route.ts, app/timequiz/TimeQuiz.module.css, app/timequiz/page.tsx
- Fixes #209 
This PR revamps the quiz functionality by replacing the static, repetitive set of questions with a **dynamic, AI-powered experience**.  
- **Before:** The quiz always pulled the same 10 questions from a local JSON file.  
- **Now:** The system integrates the Google Gemini API to generate a **fresh set of 10 questions** for every quiz session, ensuring a unique and engaging experience each time.  
Additionally, it introduces an **instant feedback mechanism**. After each answer, the user now sees whether their choice was correct along with a short, AI-generated explanation — making the quiz both interactive and educational.  
- **Dynamic Question Generation**  
- Removed the static `questions.json` source.  
- Added a new API route: `/api/generate-quiz` → Calls Gemini API to …
=> Integrated Gemini API for dynamic quiz generation (with new questions each time) & instant feedback 

app/api/quiz-results/[userId]/recent/route.ts, app/api/quiz-results/[userId]/route.ts, app/api/quiz-results/[userId]/stats/route.ts, app/api/quiz-results/route.ts, app/timequiz/TimeQuiz.module.css, app/timequiz/page.tsx, models/quizSchema.ts
* Fixes #230 
Previously, quiz scores were only shown immediately after completion and were not stored persistently. This made it impossible to track user progress, display quiz history, or show performance insights on the profile/progress page.
This PR implements **persistent quiz result storage** using MongoDB + Mongoose and integrates it with the frontend quiz component. Now, after finishing a quiz, the score (along with metadata like total questions, correct answers, quiz type, etc.) is automatically saved to the backend. This enables long-term tracking, future analytics, and gamification features.
* Created a **Mongoose schema** `QuizResult` with the following fields:
* `userId` (ref to `User`)
* `quizId`
* `score`
* `totalQuestions`
* `correctAnswers`
* `quizType` (enum: `"MCQ"`, …
=> Implemented quiz backend frontend

app/api/testimonial/post/route.ts, app/api/testimonial/route.ts, app/page.tsx, components/MarqueeDemo.tsx, models/Testimonials.ts
* Fixes #232
The testimonial section was previously hard-coded and used an external Google Form for collecting feedback, which felt unprofessional and disrupted the user experience.
This PR introduces a **custom testimonial form** with full backend + frontend integration, enabling dynamic testimonials stored in the database.
* Created backend API routes:
* `api/testimonial/post` (POST route to store testimonials)
* `api/testimonial` (GET route to fetch testimonials)
* Implemented a database model to handle testimonial data (Name, Role, Testimonial, Rating, etc.).
* Built a modal-style form component on the frontend with validation, replicating the Google Form fields.
* Integrated form submission with backend API routes to store and retrieve testimonials dynamically.
* Updated testimonial …
=> Implmented Dynamic-Testimonial-System

app/flashcards/page.tsx, components/AuthButtons.tsx, components/Filters.tsx, components/Flashcard.tsx, components/FlashcardComponent.tsx, components/ProgressBar.tsx, data/flashcards.ts, lib/types.ts, lib/useLocalStorage.ts
- Fixes #121 
This PR introduces a Flashcard Mode feature, enabling users to quickly review and reinforce their knowledge through an interactive experience.
- Added Flashcards Page – A dedicated section for flashcard-based practice.
- Filter Options – Users can filter flashcards by difficulty level and topics for a personalized experience.
- Interactive Progress Tracking – Each time a flashcard is flipped, the progress bar updates in real-time.
- Reset Options – Users can reset filters and progress as needed (progress reset is limited to the frontend only).
For navigation
Page layout
Working flow 
https://github.com/user-attachments/assets/ddba0145-eff5-419c-a220-53bf7d19d4f1
> Note: Please ensure that appropriate labels (like `gssoc25` and level labels) are assigned to the **merged PR**. …
=> Flashcards 

components/POTD.tsx, components/SheetContent.tsx
* Fixes #249 
Currently, unauthenticated users are able to mark problems as solved or “done” in the sheet, which breaks personalized tracking, causes unreliable analytics, and poses a security concern (anyone can spam updates).
This PR introduces **auth validation on both frontend and backend**, ensuring that only logged-in users can update progress. Additionally, I added a **modal popup** to prompt visitors to sign in when they attempt restricted actions, improving UX.
* Added **frontend auth guard** for “Mark as Done” and “Solved” checkboxes
* If unauthenticated → show modal popup and redirect to signin page
* Added **toast notification** for better UX (`Login required to track your progress`)
* Secured backend endpoints (`/api/progress/markDone`, `/api/progress/updateSheet`) with JWT …
=> Added validation in sheet page

app/globals.css, app/page.tsx, components/AuthButtons.tsx
* Fixes #259 
This PR addresses the navigation issue for the **"Give Testimonial"** button in the navbar.
Previously, the button redirected users to an **external Google Form**, taking them outside the platform and creating a broken user flow. The intended behavior was to link it to the **new in-built testimonial form**, which stores user input in the backend database and displays it dynamically in the testimonial section.
While working on this issue, I discovered that the testimonial form was designed to be used as a **modal component** rather than a dedicated page. Because of this, simply linking the navbar button to the existing form wasn’t possible.
* **Implemented a new integration** for the testimonial modal so it can be triggered directly via the navbar.
* **Rebuilt the modal logic …
=> Added the similar modal for form of testimonial response taker from user

app/notes/page.tsx
* Fixes #254 
The testimonial section had an issue where the **"Give Testimonial"** button inside the navbar redirected users to an **external form outside the website**. This broke the expected navigation flow and created a poor user experience.
This PR fixes that issue by ensuring that the **"Give Testimonial"** button now correctly routes users to the **testimonial form within the application** itself, maintaining consistency and improving usability.
* Updated the **navigation logic** for the "Give Testimonial" button.
* Ensured the button uses **internal routing** instead of redirecting outside.
* Added a reusable component (`TestimonialButton`) with proper routing.
* Verified responsive behavior for both desktop and mobile views.
1. Navigate to the **navbar** and click the **"Give …
=> Added filter for supereme 3.0 and pattern wise notes in notes page

app/timequiz/page.tsx
- Fixes #153
Previously, once a user started a quiz, there was no way to exit or go back without completing it or closing the tab. This created a poor user experience, especially if a user started the quiz by mistake. This PR solves the issue by implementing an "Exit" button on the quiz screen. To prevent accidental data loss, clicking the button triggers a confirmation modal, allowing the user to either cancel and resume the quiz or confirm their decision to exit.
- Added a new state variable (`showExitModal`) to manage the visibility of the confirmation modal.
- Implemented an "Exit" button in the UI of the active quiz screen.
- Created a confirmation modal component that appears when the exit button is clicked.
- Added a `handleExitQuiz` function that resets the quiz state, effectively …
=> Fix: Added the back navigation in quiz with prompting 

components/Footer.tsx
- Fixes #265 
The footer section had inconsistent styling that did not align with the overall website theme. This PR addresses the visual presentation issues by implementing proper design system integration.
- **Color Scheme**: Replaced hardcoded colors with design system tokens:
- `bg-background` instead of `bg-white dark:bg-[#121212]`
- `text-foreground` instead of `text-gray-900 dark:text-white`
- `text-muted-foreground` instead of `text-gray-600 dark:text-gray-400`
- `border-border` instead of `border-gray-300 dark:border-gray-800`
- Updated font weights to use consistent `font-bold` instead of `font-semibold`
- Improved text sizing and spacing for better hierarchy
- Enhanced readability with proper line-height and spacing
- Added smooth motion animations using `framer-motion`
- …
=> fix: improve footer styling consistency with design system

components/AuthButtons.tsx
- Fixes #266 
The dropdown menu component (part of user profile and navigation) did not properly adapt to the website's light theme. While the dark mode version appeared correctly styled, the light mode version retained dark-themed styling, creating visual dissonance and poor UX in light mode.
- **Background**: Replaced hardcoded `bg-gradient-to-tl from-blue-950/90 via-neutral-950/90 to-neutral-950/90` with `bg-popover`
- **Text Colors**: Updated from `text-gray-200` and `text-white` to `text-foreground` and `text-muted-foreground`
- **Borders**: Changed from `border-white/10` to `border-border`
- **Hover States**: Updated from `hover:bg-white/10` to `hover:bg-muted`
- **Dropdown Container**: Now uses `bg-popover` with proper `border-border`
- **Menu Items**: Use `text-foreground` for …
=> fix: resolve light mode dropdown menu theme inconsistency

app/(auth)/changePassword/changePassword.tsx, app/code-analyzer/layout.tsx, app/code-analyzer/page.tsx, app/email-preference/content.tsx, app/privacy-terms/page.tsx, app/question/[slug]/page.tsx, lib/openaiAnalyze.ts, package-lock.json, package.json, pages/api/openai-analyze.ts, tsconfig.json
Added a comprehensive Code Analyzer page that allows users to paste code snippets and get instant Time and Space Complexity analysis. The feature supports multiple programming languages (C++, Java, Python) and offers both fast static heuristics and AI-powered analysis using Google Gemini for more accurate results.
- Created `/app/code-analyzer/page.tsx` with responsive UI including code input textarea, language dropdown, and analysis mode selector
- Implemented static complexity analysis with heuristics for loops, recursion, and memory allocation detection
- Added AI-powered analysis integration using Google Gemini API via `/pages/api/openai-analyze.ts`
- Created `/lib/openaiAnalyze.ts` utility for API communication
- Added `/app/code-analyzer/layout.tsx` for consistent styling
- Fixed …
=> Resolved vercel conflicts

components/AuthButtons.tsx, components/Navbar.tsx, components/NavbarSheet.tsx
=> chore: commit all workspace changes

app/globals.css, components/FlashcardComponent.tsx
- Fixes #277 
Fixed critical UI corruption and data rendering bugs in the flashcard component that made it completely unusable. The component now properly displays flashcard content with smooth 3D flip animations and robust error handling.
**1. CSS Utilities (app/globals.css)**
✅ Added essential 3D transform utilities with cross-browser support
✅ Added hardware acceleration optimizations
✅ Added comprehensive flashcard-specific CSS classes
**2. Component Optimization (components/FlashcardComponent.tsx)**
✅ Complete rewrite with robust error handling
✅ Performance optimization using useMemo
✅ Simplified and more reliable 3D flip animation
✅ Better state management and null checks
**🧪 Testing Checklist**
✅ Flashcards display properly without text corruption
✅ 3D flip animation works …
=> fix: resolve critical flashcard UI corruption and data rendering issues

app/globals.css, app/sheet/page.tsx, components/NavbarSheet.tsx
- Fixes #278 
**Problem:**
- Navbar was overlapping the "Your Progress" section on mobile viewports in /sheet page
- NavbarSheet component has dynamic height (~84px mobile) but insufficient top padding was applied
- Mobile hamburger menu functionality was broken
**Solution:**
- Added CSS utility classes for proper navbar spacing
- Applied navbar-offset-sheet class to sheet page main content
- Cleaned up mobile navigation in NavbarSheet component
- `app/globals.css` - Added navbar spacing utilities
- `app/sheet/page.tsx` - Applied proper top padding
- `components/NavbarSheet.tsx` - Fixed mobile navigation
**Before:**
**After:**
1. Mobile viewport: Header fully visible, no overlap
2. Desktop viewport: Proper spacing maintained  
3. Mobile hamburger menu: Working correctly
> Note: Please …
=> Fix: Navbar overlaps page header on mobile viewports in /sheet page

app/code-analyzer/layout.tsx, app/code-analyzer/page.tsx
- Fixes #318 
- Created animated code complexity analyzer page
- Implemented DSAMate-themed dark UI with glassmorphism effects
- Added support for C++, Java, Python languages.
- `layout.tsx` - Added client-side animated background
- `page.tsx` - Implemented main analyzer component with form controls and results display
1. Navigate to `/code-analyzer` route
2. Paste code sample in textarea
3. Select language and analysis mode
4. Click "Analyze Code" button
5. View time/space complexity results
=> feat: Enhanced Code Analyzer Page with Modern UI

app/api/questions/route.ts, app/api/test/route.ts, app/sheet/page.tsx, app/test-api/page.tsx, components/SheetContent.tsx, db/config.ts, debug-api.js, lib/questionsApi.ts, lib/questionsApiExamples.ts, models/Question.model.ts, package.json, scripts/seedQuestions.ts
* Fixes #323 
Fixes a client-side issue where the **Sheet page showed continuous "Loading questions..."** even though `/api/questions` returned valid data.
Adds **defensive parsing, robust state handling, and dev-only diagnostics** in `SheetContent.tsx` to ensure topics are set reliably and the spinner clears.
* **SheetContent.tsx**
* Added defensive parsing of API response (`data.data` must be array before `setTopics`).
* Added console logs for API response and state transitions (`loading`, `topics.length`, `error`).
* Added a small dev-only debug panel (bottom-right) showing `loading`, `topics count`, and `error`.
* Added a defensive effect: if `topics.length > 0` while `loading === true`, force `setLoading(false)` to prevent stuck spinner.
* Preserved all existing UI behavior and …
=> feat: Added Questions API, Integrated with frontend

README.md, app/page.tsx, app/privacy-terms/page.tsx, app/sheet/page.tsx, components/Footer.tsx, components/NavbarSheet.tsx
- Fixes ### 338
This PR cleans up the UI and updates project naming to improve clarity and consistency:
- Removed all buttons/links that said “View Original Sheet” or redirected to DSAMate v1
- Updated UI text: replaced all mentions of “DSAMate Template” with “DSAMate v2” (Navbar, Footer, Titles, etc.)
- Updated README  where needed
-Updated FAQ and other textual content for accuracy
=> [Feature]: Remove old buttons & rename DSAMate Template → DSAMate v2

app/(auth)/sign-in/page.tsx, app/(auth)/sign-up/page.tsx
This PR resolves #337 
Updated icons such that it matches with its function (show / hide)
=> updated toggle eye icon

app/notes/page.tsx
- Fixes #321 
A hover animation of scale up and changing background of the button has been added on the "Show Favorite" button to increase its interactivity.
- scale up on hover.
- changing background of the button on hover.
https://github.com/user-attachments/assets/11242981-5cf5-42a9-b0ee-1af36c58866c
1. visit the added screen recording.
=> Hover animation added to the button

app/sheet/SheetPageClient.tsx
- Fixes #365 
This PR improves the UI/UX of the dropdown buttons (Difficulties, Solved Status, Revision Status, Platform, All Companies) by adding smooth hover animations.
- Added background color change on hover for better interactivity.
- Ensured hover states work consistently in both light and dark mode.
- changed the background of the buttons to a little darker for a better interactivity.
https://github.com/user-attachments/assets/a3397019-2606-4e8e-9ea5-d1380f872188
1. Checkout the attached screen recording.
=> hover aniamtion added on the dropdown buttons of sheet section

app/api/progress/[userId]/route.ts, app/api/progress/update/route.ts, app/progress/ProgressPageClient.tsx, app/sheet/SheetPageClient.tsx, components/ProgressStats.tsx, components/ProgressSummary.tsx, components/SheetContent.tsx, components/TopicProgress.tsx, models/Progress.model.ts
Closes #185 (partial fix)
* Implemented live sync of **solved problems** from the Sheet tab to the Progress tab.
* Progress tab now dynamically updates:
* Total solved problems
* Breakdown by difficulty (Easy, Medium, Hard)
* No manual refresh required.
*  Sync of **markedForReviewCount** is not yet implemented.  Tried it but couldn't finish it
* Marked and unmarked problems in the Sheet tab → Progress tab updated instantly.
* Verified counts across Easy/Medium/Hard update correctly.
=> Fix progress sync

app/code-analyzer/layout.tsx, app/code-analyzer/page.tsx
* Fixes #391
---
This PR revamps the **Code Analyzer page** to deliver a modern, accessible, and theme-consistent developer experience.
It transitions from a static output panel to a structured interface with **tabbed insights, contextual tips, metrics, and export capabilities** — improving usability, consistency, and accessibility across both light and dark themes.
---
* 🎨 **Unified Theming & Visual Polish**
* Replaced legacy blue accent with purple theme (light/dark variants)
* Added animated gradient pulse, improved headline & icon clarity
* Refined dark mode focus rings, borders, and contrasts
* 📊 **Result Enhancements**
* Distinct cards for Time, Space, and new **Code Metrics** (lines, characters, avg line length)
* Complexity classification: raw strings mapped to readable categories …
=> [ENH]: Enchanced code analyzer page

app/api/(auth)/check-auth/route.ts, app/api/generate-feedback/route.ts, app/api/generate-quiz/route.ts, app/api/progress/[userId]/route.ts, app/api/progress/update/route.ts, app/api/quiz-results/[userId]/recent/route.ts, app/api/quiz-results/[userId]/stats/route.ts, app/timequiz/page.tsx, models/Progress.model.ts
- Fixes [Feature]: Past Quiz Results Display and Average Score Calculation #303
Updated the quiz UI header to prevent clipping on fullscreen.
Integrated a proper Recent Attempts section with a “View More / View Less” toggle to display additional quiz attempts. Improved the styling of the toggle button for better UX.
- Added extra padding/margin to header to prevent clipping.
- Displayed recent attempts with a “View More / View Less” button.
- Styled the button with gradient, hover effects, and responsive layout.
- Kept stats (Avg Score & Total Quizzes) visible above recent attempts
https://github.com/user-attachments/assets/10694960-56cb-46b0-8100-eeb690505f18
Checkout the branch locally.
Run the app (npm run dev / yarn dev) and open the quiz page.
Verify header displays correctly on …
=> Update header UI and recent attempts section
