.gitignore
app/notes/page.tsx
app/page.tsx
app/sheet/page.tsx
components/Navbar.tsx

- Updated the navbar from fixed to floating improving the user experience
- Visually enhanced the navbar, adding a glassmorphic background giving it a clean look
<br/>
<hr/>
<hr/>
<hr/>
Corresponding issue - #6

Update navbar across all screen

---

app/sheet/page.tsx

**Fixed issue #5** 
Fixes the UI issue where opening any dropdown filter (like Platform, Difficulty, etc.) causes other filter elements to become invisible on dark backgrounds due to white dropdown options. Now, the dropdowns stay properly visible and no UI is hidden.

Fixed: Filter Section Dropdown Items Are Invisible Unless Hovered 

---

Frontend/app/progress/page.tsx

- Removed an extra `<Footer />` component on the Progress page
- Footer is now rendered only once via the global layout, ensuring consistent UI
Closes #48

fix: remove duplicate footer on Progress page

---

.github/workflows/send-potd.yml
app/api/email-preference/route.ts
app/api/send-potd/route.ts
app/email-preference/content.tsx
app/email-preference/page.tsx
models/User.model.ts

**Summary**
--
fix : #87
This PR implements an automated system to send the Problem of the Day (POTD) to subscribed users daily at 9:30 AM IST using Nodemailer and GitHub Actions.(also users can subscribe to Newsletter)
-  Added a GitHub Actions workflow (.github/workflows/send-potd.yml) to send emails to registered users automatically daily at a fixed time without any manual need.
- Scheduled daily run at 9:30 AM IST using cron (0 4 * * * UTC)
- Triggers the deployed endpoint: https://dsa-sheet-template.vercel.app/api/send-potd
- Connects to MongoDB and fetches users with subscribedToEmails: true (who've subscribed/registered)
- Sends dynamic POTD email with links and unsubscribe email  , subscribe to newsletter options
- Uses centralized sendEmail() method via Nodemailer
- Dynamically …

Send Daily POTD notifications to registered emails.

---

components/AuthButtons.tsx

This PR fixes the issue where the "Sign In" button would break into two lines and flicker between states on hover.  
The problem was caused by inconsistent padding and width behavior, which was adjusted to maintain layout stability.
- Updated `AuthButtons.tsx` to ensure consistent button dimensions.
- Prevented text wrapping on hover.
- Improved styling to keep alignment intact.
Closes #165 
On hover, the "Sign In" button would:
- Break text into two lines
- Flicker between single-line and double-line states
The button:
- Maintains single-line text at all times
- No flicker or layout shift on hover
**Before:**
https://github.com/user-attachments/assets/73b01484-a386-4fc4-a61e-1c8aa0b9b3b5
**After:**
https://github.com/user-attachments/assets/3ce74f9e-ad3e-4f3c-9223-223113cc2140
---
✅ This …

Fix: Sign In Button Flicker on Hover

---

app/contributors/page.tsx

This PR fixes the slow and inconsistent hover-out animations on contributor cards.
- Reduced Framer Motion’s hover-out transition duration to **~0.2s** for a snappier experience.
- Updated overlay fade-out duration to match the scale-down speed.
- Ensured hover-in remains instant while hover-out now feels quick and responsive.
Previously:
- Hover-out scale-down took ~4–5 seconds due to default spring animation.
- Overlay fade-out (`duration-500`) felt slower than the scale-down.
Now:
- Hover-out feels smooth and fast.
- Overlay and scale animations are perfectly synchronized.
---
Closes #167 
---

Fix: Snappier Hover-out Animation for Contributor Cards

---

app/contributors/page.tsx
app/page.tsx

This PR addresses a text contrast issue that made certain UI elements hard to read in light mode.  
Specifically:  
- **Contributors Page**: The hover overlay text `"Visit Profile"` previously used white text, which had low visibility in light mode.  
- **Home Page**: The `"Visit Original DSAMate"` button also had white text in light mode, blending into the background and reducing readability.  
---
- Updated styles for `"Visit Profile"` overlay text to ensure sufficient contrast in both light and dark modes.  
- Updated `"Visit Original DSAMate"` button text color to adapt based on theme or use a high-contrast color by default.  
---
---
1. Switch the site to **light mode**.  
2. Go to the **Contributors** page and hover over any contributor card → text should be clearly visible.  
3. Go …

Fix: Improve text contrast for "Visit Profile" and "Visit Original DSAMate" in light mode

---

components/NavbarSheet.tsx

This PR fixes an issue where the **navigation bar** on the `/sheet` page was **invisible by default** and only became visible when hovered over.  
This behavior caused poor usability and discoverability for users unfamiliar with the site layout.
---
- Updated the navbar styling to ensure it is visible on page load.
- Applied theme-consistent colors to maintain good visibility in both light and dark modes.
- Verified that hover styles still work without hiding default visibility.
- Ensured WCAG-compliant contrast ratio for accessibility.
---
- Navbar text/icons were hidden by default.
- Only visible when hovering over the navbar area.
- Navbar items are visible immediately when the page loads.
- No loss of hover interactivity.
---
1. Open the site in **light mode**.
2. Navigate to `/sheet` …

Fix: Navbar Visibility on Sheet Page

---

.github/workflows/send-potd.yml
app/api/send-potd/route.ts
models/JobRun.model.ts

fix : #87 — Secure Daily POTD Emails
This PR fixes the issue of **emails being sent multiple times per day** and secures the daily “Problem of the Day” (POTD) email job.
---
* **Public endpoint:** `GET /api/send-potd` was public. Bots, uptime monitors, and forks could trigger it.
* **Multiple callers:** Forked repos with the same GitHub Actions workflow triggered your production endpoint.
* **No idempotency:** Every request sent emails, no check if it already ran that day.
---
1. **Endpoint security**
* Endpoint now requires header `x-cron-secret` (or query `?key=`) matching `process.env.CRON_SECRET`.
* Unauthorized requests **won’t send emails**.
2. **Idempotent daily job**
* Added `models/JobRun.model.ts` to track runs per day (IST).
* If already run today, it exits without sending …

Following up previous PR Secure Daily POTD Emails

---

components/SheetContent.tsx

* Fixes #200 
Child components currently render with sharp edges and no border radius, creating a visual inconsistency compared to their parent containers which have rounded corners and shadows.
This PR applies consistent border radius to nested elements to ensure a unified UI.
* Added `border-radius` to child containers.
Before:
After : 
1. Pull this branch locally.
2. Navigate to a page where nested components are rendered. (/sheet)
3. Verify that child elements now have consistent rounded corners.

Added border radius for nested div

---

app/page.tsx

- Fixes #221
Implemented single FAQ expansion functionality to improve user experience and readability. Now only one FAQ can be expanded at a time, preventing content overflow and making it easier for users to focus on one question at a time.
https://github.com/user-attachments/assets/49c9767c-52af-4b31-a5e3-2da6ef8b74d5

fix: Single FAQ expanded at a time

---

app/layout.tsx
components/ScrollToTopBottom.tsx

- Fixes #233
The ScrollToTopBottom button was only appearing on the Home page. This PR ensures that the button is visible on all pages by adding it to the main layout component (layout.tsx), allowing users to scroll to the top or bottom from any page.
- Added "use client" directive to ScrollToTopBottom.tsx.
- Added <ScrollToTopBottom /> component in layout.tsx so it renders on all pages, not just Home.
- Maintained smooth scroll-to-top and scroll-to-bottom functionality.
1. Navigate to any page (Home, Sheet, Notes, etc.) in the app.
2. Scroll down until the ScrollToTopBottom button appears.
3. Click the up or down arrow to verify smooth scrolling works correctly.
> …

Fix: ScrollToTopBottom button appears on all pages

---

components/ScrollToTopBottom.tsx

* Fixes #255 
The **Scroll to Top** and **Scroll to Bottom** buttons were overlapping with notifications in the bottom-right corner. This made notifications difficult to view and interact with.
This PR repositions the scroll buttons to the **bottom-left corner**, ensuring a cleaner and more user-friendly layout.
* Updated button container position from `bottom-right` to `bottom-left`
* Verified alignment and spacing on different screen sizes
* Ensured accessibility and visibility in both light and dark themes
**Before:**
**After:**
1. Trigger a notification in the app (bottom-right corner).
2. Verify scroll buttons are now placed in the bottom-left corner.
3. Ensure scroll buttons function as expected (scroll to top/bottom).

fix: reposition scroll buttons to avoid overlap with notifications

---

app/companies/page.tsx
app/layout.tsx
components/CompanyProgressSummary.tsx
components/CompanyQuestionsList.tsx
components/CompanySelector.tsx
components/Navbar.tsx
contexts/QuestionContext.tsx
data/companyQuestions.ts

- Fixes #112
Implemented the *Company-wise Questions Page*.
This PR adds a dedicated page where users can browse DSA questions company-wise.  
Users can select a company (Google, Amazon, Microsoft, etc.) and view all relevant questions.  
Dummy data is used initially, and the "Mark as Done" status is synced across companies.
- Added company selector UI .
- Displayed dummy company-wise question lists.
- Synced "Mark as Done" status across companies.
- Built modular, reusable components for scalability.
1. Navigate to the `Company-wise Questions Page`.
2. Select a company (e.g., Google, Amazon).
3. Verify that relevant dummy questions are displayed.
4. Mark a question as done and confirm it reflects across companies where it exists.
> Note: Please ensure that appropriate labels (like …

Feat: Add Company-wise Questions Page (Fixes #112)

---

app/code-analyzer/page.tsx

Problem:
The dropdown options for "Language" and "Analysis Mode" in the Code Analyzer page were invisible due to white text on a white background (or poor contrast in dark mode). This affected usability and accessibility.
Solution:
Added a scoped CSS rule to ensure dropdown options are visible in both light and dark modes.
No changes were made to globals.css—the fix is isolated to the CodeAnalyzerPage component.
Changes:
Added .dropdown-visible class to <select> elements.
Used <style jsx> to override dropdown option styling for better contrast.
Testing:
Verified dropdown visibility in both light and dark modes.
Confirmed no unintended side effects on other components.

fix: dropdown options visibility in light/dark mode

---

app/(auth)/layout.tsx
app/api/questions/README.md
app/api/questions/route.ts

* Fixes #324
Added a **POST endpoint at `/api/questions`** for upserting topics or adding questions.
Requires authentication (JWT session cookie).
Added runtime validation for payloads, updated docs, and fixed a TypeScript static image import error.
* **route.ts**
* Added POST handler with payload validation, auth check, and upsert/add logic.
* Returns appropriate error codes (400/401/403/404/409/500).
* **README.md**
* Added usage docs with example payloads and a `curl` test command.
* **layout.tsx**
* Removed static image import.
* Updated backgroundImage to `url(/assets/banner.png)` to fix TS2307 image import error.
1. Start dev server and log in as any user to obtain session cookie (JWT).
2. Run `npx tsc --noEmit` — confirm no TypeScript errors.
3. Test with curl (example):
```bash …
```

feat: Added Post Route for questions

---

LEARN.md
README.md

This PR updates the project documentation to reflect the correct project name. The term “DSAMate Template” has been replaced with “DSAMate v2” across relevant files. The context of the documentation has also been restructured to represent DSAMate v2 as the unique and contributor-friendly project under GSSoC 2025.
- Updated README.md to replace all mentions of “DSAMate Template” with “DSAMate v2”
- Updated learn.md with the new project name and context
- Removed references that implied the repo was just a template
- Improved wording to highlight DSAMate v2 as the main project open for contributions
Screenshots 
1.Open the updated README.md and confirm that all instances of “DSAMate Template” are now “DSAMate v2”
2.Review learn.md to ensure the context matches the new project identity …

[update]-updated the readme.md learn.md files according to the project requirements.

---

app/api/questions/route.ts
components/SheetContent.tsx
db/config.ts

The questions fetched from the database were being returned in an unsorted/shuffled order, which affected the consistency of the UI and user experience.
This PR updates the backend route to ensure that questions are **sorted by their `id` field** before being sent in the API response.
* Updated the database query logic in the backend route.
* Applied sorting using `a.id - b.id` to return questions in ascending order.
* Ensured consistent order of questions across API responses.
1. Start the backend server.
2. Call the API endpoint for fetching questions.
3. Verify that the returned questions are sorted in ascending order by ID.
> Note: Please ensure that appropriate labels (like `gssoc25` and level labels) are assigned to the **merged PR**.
> Sometimes it may be missed by PA or mentors, …

feat: Made Question fetch in sorted order

---

app/cp-tracker/CPTrackerPageClient.tsx
utils/leetcode.ts

- Fixes #373 
- Previously, the "Total Active Days" metric always showed 0 for all users.  
- This PR replaces it with **Total Submissions** (sum of solved problems) across all platforms: Codeforces, LeetCode, and HackerEarth.  
- Now, the dashboard correctly fetches and displays submission stats for all supported platforms.
- Updated `utils/leetcode.ts` and frontend logic to calculate total solved submissions instead of Active Days.
- Updated `CPTrackerPageClient` to reflect "Total Submissions" on the dashboard.
- Verified that stats fetch correctly for Codeforces, LeetCode, and HackerEarth.
| Platform        | Dashboard Screenshot |
|-----------------|-------------------|
| **Codeforces**  | <img width="800" height="400" alt="Screenshot (992)cf" …

Fix: Replace Total Active Days with Total Submissions across all CP platforms

---

app/globals.css
components/BotWidget.tsx

- Fixes #366
Made the BotWidget component fully responsive across all screen sizes (smartphones, iPhones, tablets, laptops, and desktops) without disrupting the overall webpage layout. The bot widget now provides optimal user experience on all devices while maintaining functionality and visual appeal.
- Replaced JavaScript-based screen size calculations with Tailwind CSS responsive classes for better performance
- Implemented mobile-first responsive design approach with appropriate breakpoints
- Added responsive sizing for bot button (w-12 on mobile to w-24 on desktop)
- Made chat window dynamically sized (w-80 on mobile to w-[480px] on large screens)
- Implemented responsive text sizing (text-sm to text-base across breakpoints)
- Added responsive padding and spacing throughout the …

updated botwidget responsiveness for all screentype

---

components/mode-toggle.tsx
components/ui/conceptCard.tsx
data/flashcards.ts

- Fixes #315 
Problem was to add new flashcards.
- Earlier there were only 17 flashcards
- Added 33 more. Total 50 flashcards available on different topics.
- 
1. Run the project locally
2. Go to theory cheatsheets and flashcards section in learning tools
3. View the flashcards
4. 
- [ x] I linked a related issue using `Fixes #315 
- [ x] I am GSSoC'25 contributor
- [x ] I am Hacktoberfest'25 contributor
- [x ] I tested locally and verified the changes work as expected
- [x ] I updated docs or comments where needed

Added new Flashcards

---

components/POTD.tsx
components/SheetContent.tsx

* Fixes #384
---
This PR implements the **one-way sync feature** from **POTD → DSA sheet**, ensuring progress is consistently tracked while maintaining independence of POTD’s date-based behavior.
The solution satisfies all acceptance criteria:
* Marking POTD as done automatically checks the corresponding DSA list question.
* Repeated POTD questions always start unchecked (date-based status).
* DSA sheet updates do not affect POTD (strict one-way sync).
* All changes persist reliably in `localStorage` with real-time UI updates.
---
* 🔧 **Enhanced POTD Component**
* Added robust question matching logic (by ID + title).
* Implemented sync logic with custom event dispatch for real-time UI updates.
* 🔧 **Enhanced SheetContent Component**
* Added `localStorage` change listeners for …

[FEAT]: Sync POTD and Mark as Done
